# Creates database gaaacha if missing. Pass password as first arg.
# Usage: .\scripts\setup-postgres.ps1 "your_postgres_password"
param(
  [Parameter(Mandatory = $true)]
  [string]$Password
)

$ErrorActionPreference = "Stop"
$psql = "C:\Program Files\PostgreSQL\18\bin\psql.exe"
if (-not (Test-Path $psql)) {
  throw "psql not found at $psql - is PostgreSQL 18 installed?"
}

$env:PGPASSWORD = $Password
$env:PGCLIENTENCODING = "UTF8"

Write-Host "Checking connection..."
& $psql -U postgres -h 127.0.0.1 -p 5432 -d postgres -c "SELECT version();"

$exists = & $psql -U postgres -h 127.0.0.1 -p 5432 -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='gaaacha'"
$exists = ($exists | Out-String).Trim()
if ($exists -eq "1") {
  Write-Host "Database gaaacha already exists."
} else {
  Write-Host "Creating database gaaacha..."
  & $psql -U postgres -h 127.0.0.1 -p 5432 -d postgres -c "CREATE DATABASE gaaacha;"
  Write-Host "Created."
}

$envPath = Join-Path (Join-Path $PSScriptRoot "..") ".env"
$url = "postgresql://postgres:${Password}@127.0.0.1:5432/gaaacha"
Set-Content -Path $envPath -Value "# Generated by scripts/setup-postgres.ps1`nDATABASE_URL=$url`n" -Encoding ASCII

Write-Host "Wrote $envPath"
Write-Host "Done. Start server with: npm run dev"
Write-Host "Look for: Postgres connected - schema applied"
